Added multilingual mode (#116)
cryptic-game/website pull request #170
Opened 2021-05-13 17:35 UTC by MarcelCoding

**Description**
Add the possibility to change between english and german

**Issue**
Closed #80 

**TODO**
- Translate contribute page -> Text not translated yet
- use translation of Ghost Blog Posts

2021-06-15 11:22 UTC, Akida31 requested changes

2021-06-15 11:22 UTC, Akida31 commented on components/LanguageSwitcher.vue
> +  //border-radius: 5px;
remove this?

2021-06-15 11:22 UTC, Akida31 commented on components/LanguageSwitcher.vue
> +  background-color: rgba(255, 255, 255, 0.25);
background color should have a higher alpha value. With 0.25 the text of the language switcher is not easy readable if there was other text (for example the typed slogans) in the background

2021-06-15 11:22 UTC, Akida31 commented on components/NavigationBar.vue
> +        <span class="navigation-bar__title">{{ title }}</span>
translate the title -> 
`<span class="k-navigation-bar__title">{{ $t("navbar." + title) }}</span>`

2021-06-15 11:22 UTC, Akida31 commented on pages/contribute.vue
> +        {{ $t("contribute.content.first-setps") }}
typo: `setps` -> `steps`

2021-06-15 11:22 UTC, Akida31 commented on components/NavigationBar.vue
>    font-size: 1.5rem;
font size should be smaller because if you visit the German version of contribute the content of the navigation bar is bigger than its size

2021-06-15 11:56 UTC, Akida31 submitted a review, later dismissed

2021-06-15 16:41 UTC, JannikEmmerich submitted a review, later dismissed

2021-06-15 16:46 UTC, aronck8 approved these changes

2021-06-15 21:44 UTC, JannikEmmerich approved these changes

2021-06-15 21:45 UTC, JannikEmmerich submitted a review, later dismissed

2021-06-16 18:54 UTC, DevMimas approved these changes

2021-06-16 18:58 UTC, JannikEmmerich approved these changes

2021-06-16 19:00 UTC, merged