Überschriften linksbündig
cryptic-game/website pull request #204
Opened 2021-06-22 15:37 UTC by 1Spinne

**Description**
> Macht Überschriften linksbündig, damit sie besser auf kleinen Bildchsirmen angezeigt werden.

2021-06-22 16:16 UTC, MarcelCoding requested changes
Please run the linter

2021-06-22 16:35 UTC, 1Spinne reviewed
OK

2021-06-22 16:36 UTC, 1Spinne reviewed
So richtig?

2021-06-22 16:40 UTC, 1Spinne reviewed
Jetzt richtig?

2021-07-16 16:50 UTC, 1Spinne commented
Wird das auch noch genemigt?

2021-07-16 17:59 UTC, MarcelCoding commented
@DevMimas

2021-07-16 19:15 UTC, JannikEmmerich requested changes
Well, this pull request won't change anything, or am I missing something?

2021-07-16 19:33 UTC, 1Spinne commented
Die Überschriften wurden linksbündig gemacht, weil das auf dem Handy sonst richtig blöd aussieht

2021-07-16 19:36 UTC, MarcelCoding commented
But only on the contributing page.

2021-07-16 22:07 UTC, JannikEmmerich commented
I don't see any problem.

iPhone X: 
![image](https://user-images.githubusercontent.com/22866859/126012923-6fa363a5-d17e-44bc-bea2-39a2dc4dbd22.png)

Galaxy S5: 
![image](https://user-images.githubusercontent.com/22866859/126012961-d3693207-198c-41a3-9e7e-d8c6ef807e60.png)

2021-07-18 06:20 UTC, 1Spinne commented
![93214714-55AC-46ED-A503-6834EF4C7F65](https://user-images.githubusercontent.com/66938161/126057761-ed60d03a-08f2-42ce-9915-b04e2f124b01.png)

e. g. This

2021-07-18 06:20 UTC, 1Spinne commented
iPhone SE 1. Gen

2021-07-18 08:31 UTC, MarcelCoding commented
But you only changed the css on the contributing page

2021-07-18 09:27 UTC, 1Spinne commented
![973F4A53-056D-4E6A-9638-9C70B0611D45](https://user-images.githubusercontent.com/66938161/126062287-5624f3c6-44c3-4102-98d4-ed02f31f24dd.png)
And on the start page

2021-07-18 09:34 UTC, MarcelCoding commented
nvm

2021-07-30 15:36 UTC, JannikEmmerich approved these changes

2021-07-30 15:38 UTC, MarcelCoding approved these changes

2021-07-30 15:38 UTC, merged

2021-08-24 20:03 UTC, MarcelCoding commented on pages/index.vue
> +    text-align: left;
Revert this

2021-08-24 20:04 UTC, MarcelCoding commented on pages/index.vue
> +    text-align: left;
@1Spinne do you wan't to do this
following: https://discord.com/channels/454739001841025024/533334373026627585/879816758423355482