Adds ThemeColor
cryptic-game/website pull request #240
Opened 2021-08-26 12:28 UTC by 1Spinne

Adds the theme-color for several browsers.

2021-08-31 19:21 UTC, MarcelCoding approved these changes

2021-09-01 14:55 UTC, JannikEmmerich requested changes

2021-09-01 14:55 UTC, JannikEmmerich commented on nuxt.config.js
>        }
```suggestion
      {
        name: 'theme-color',
        content: '#000000'
      }
```

2021-09-01 15:04 UTC, MarcelCoding approved these changes

2021-09-01 15:06 UTC, merged