Removed footer margin closing #252
cryptic-game/website pull request #262
Opened 2021-09-12 09:48 UTC by ClientCrash

Closes #252

2021-09-12 10:47 UTC, MarcelCoding requested changes

2021-09-12 10:47 UTC, MarcelCoding commented on components/Footer.vue
>    position: sticky;
```suggestion
  padding-bottom: 40px;
  position: sticky;
```

2021-09-12 12:11 UTC, MarcelCoding approved these changes

2021-09-19 13:17 UTC, JannikEmmerich approved these changes

2021-09-19 13:19 UTC, merged