Improved language switcher
cryptic-game/website pull request #302
Opened 2021-10-23 11:28 UTC by ClientCrash

**Issue**
Closes #303

2021-10-30 17:05 UTC, MarcelCoding commented on package.json
> +    "vue-clickaway": "^2.2.2"
> Published 4 years ago
Ether we should use another liberty or copy/fork the code to our repo. (If you do so, please include a GitHub Link to the original project.)

2021-12-23 08:21 UTC, MarcelCoding requested changes

2021-12-23 08:21 UTC, MarcelCoding commented on package.json
> +    "vue-clickaway": "^2.2.2"
^^ @ClientCrash

2021-12-23 08:21 UTC, MarcelCoding commented on components/LanguageSwitcher.vue
> +  color: #50AF2F;
I would use white rather than blue.

2021-12-24 19:20 UTC, ClientCrash commented
Todo:
- [ ] Return to old location
- [ ] set color to white

2021-12-25 11:49 UTC, MarcelCoding approved these changes

2021-12-25 15:12 UTC, DevMimas approved these changes

2021-12-25 16:00 UTC, merged