SEO optimization
cryptic-game/website pull request #351
Opened 2022-02-27 23:02 UTC by ClientCrash

**Issue**
Closes #344

2022-03-05 18:23 UTC, MarcelCoding requested changes

2022-03-05 18:23 UTC, MarcelCoding commented on pages/blog/_slug.vue
> +    if (post.author == undefined) {
```suggestion
    if (!post.author) {
```

2022-03-05 18:23 UTC, MarcelCoding commented on pages/blog/_slug.vue
> +    console.log(post)
```suggestion
```

2022-03-05 18:23 UTC, MarcelCoding commented on pages/blog/_slug.vue
> +        { hid: 'author', name: 'author', content: this.post.author }
Maybe don't use author unknown. Just don't include this meta tag.

2022-03-07 16:34 UTC, EggerWebdesign commented
Keywords are missing

2022-03-07 17:21 UTC, MarcelCoding commented
@EggerWebdesign https://github.com/MarcelCoding/m4rc3l.de/blob/main/pages/blog/_slug.vue#L109-L130 what about this method? cc. @ClientCrash

2022-03-11 13:39 UTC, MarcelCoding commented
1. replace special chars with spaces
2. split on spaces
3. to lowercase
4. count how often every word is used
5. find the top 15
6. return the top 15 joined by `, `

2022-03-11 13:44 UTC, Webkinger commented
Currently you can do it this way but later I would still make that you can edit/type the keywords Manuel in the admin panel.

2022-05-14 17:54 UTC, MarcelCoding approved these changes

2022-05-14 20:46 UTC, MarcelCoding commented
Are the keywords still relevant or can this be merged?

2022-05-15 18:50 UTC, Webkinger commented
Seo technically, keywords are important

2022-05-16 09:39 UTC, MarcelCoding commented
@ClientCrash do you want to implement keywords?

2022-05-16 14:29 UTC, MarcelCoding approved these changes

2022-07-10 17:24 UTC, DevMimas approved these changes

2022-07-10 17:24 UTC, merged