Issue/78 update roadmap to pre alpha 3
cryptic-game/website pull request #84
Opened 2020-09-02 14:16 UTC by ULUdev

I worked on the roadmap page (especially the pre-aplha 3 part).

2020-09-02 14:43 UTC, MarcelCoding requested changes
Please format the code.
Add the issue Number to the commit messages.
Improve the commit messages. (https://wiki.cryptic-game.net/link/137#bkmrk-2.1-commit-message)
Add a E-Mail Address to your commit's.

2020-09-02 16:18 UTC, JannikEmmerich commented
@ULUdev Bitte in Zukunft die > Zeichen vom Template entfernen, damit die Pull Request Nachricht richtig angezeigt wird.
Ich hab das mal für dich geändert, in Zukunft weißt du es ja ;)

2020-09-02 16:19 UTC, ULUdev commented
@JannikEmmerich Danke. Ich muss mich hier auch erstmal reinfinden

2020-09-02 17:06 UTC, MarcelCoding approved these changes

2020-09-02 17:06 UTC, JannikEmmerich approved these changes

2020-09-04 15:42 UTC, JannikEmmerich submitted a review, later dismissed

2020-09-04 15:43 UTC, MarcelCoding submitted a review, later dismissed

2020-09-14 15:08 UTC, merged