fixed that button open new tabs
cryptic-game/website pull request #90
Opened 2020-09-19 23:54 UTC by Chaozz66

**Description**
> push on play buttons open a new tab now

**Issue**
#89

**Testing Instructions**
>test local build

**Additional Notes**
> Add any other context about the pull request here.

2020-09-19 23:57 UTC, MarcelCoding requested changes

2020-09-19 23:57 UTC, MarcelCoding commented on components/KNavigationBar.vue
> -                rel="noopener"
add `rel="noopener"` that the page from which you are redirected can't track the website from which you are

2020-09-19 23:57 UTC, MarcelCoding commented on pages/index.vue
> +          target="_blank"
add `rel="noopener"` that the page from which you are redirected can't track the website from which you are

2020-09-19 23:57 UTC, MarcelCoding commented on pages/index.vue
> +        <CButton green href="https://play.cryptic-game.net" target="_blank" outline text-color="white">
add `rel="noopener"` that the page from which you are redirected can't track the website from which you are

2020-09-20 00:05 UTC, MarcelCoding submitted a review, later dismissed

2020-09-20 00:10 UTC, JannikEmmerich submitted a review, later dismissed

2020-09-20 00:11 UTC, MarcelCoding submitted a review, later dismissed

2020-09-20 00:11 UTC, JannikEmmerich submitted a review, later dismissed

2020-09-20 00:12 UTC, MarcelCoding submitted a review, later dismissed

2020-09-20 00:14 UTC, JannikEmmerich approved these changes

2020-09-20 00:14 UTC, MarcelCoding approved these changes

2020-09-20 00:15 UTC, merged